name: arithmetic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Fmt
      run: cargo fmt --check
    - name: Run tests
      run: cargo test --verbose

  release:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.result == 'success'

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        cargo install cargo-release

    - name: Release
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        echo "Releasing a version..."
        cargo release --execute

    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish
    
    


